### ISSUE TITLE
3rd party library versions

### ISSUE THREAD

**Issue by sandeep-sm** [HenryLittle/GloFE#4]
One needs to install these specific versions of the mentioned libraries, without which there will be multiple library mismatches. Adding them to your Readme would make it easier for the future users:

MMPose - v0.29.0
mmcv==1.6.2
mmdet==2.25.2
mmtrack>=0.6.0
xtcocotools==1.12

**Comment by ROYLYZ** [comment]
Thanks a lot!

**Comment by HenryLittle** [comment]
@sandeep-sm Sorry for the delay and thanks for your advice. I added this information in the README file.

**Comment by sandeep-sm** [comment]
Glad I could help :)
